import React,{useRef,useState} from 'react';
import {Alert,Dimensions,ScrollView,Share,StyleSheet,Text,TextInput,TouchableOpacity,View} from 'react-native';
import * as MediaLibrary from 'expo-media-library';
import * as Sharing from 'expo-sharing';
import {captureRef} from 'react-native-view-shot';
import {StatusBar} from 'expo-status-bar';
import {Ionicons} from '@expo/vector-icons';

const W=Dimensions.get('window').width; const API=(require('../app.json') as any).expo.extra.apiBaseUrl;
type Slide={hook:string;title:string;text:string};
type Result={title:string;subtitle:string;wow:string;cards:{title:string;text:string}[];slides:Slide[];sources:{title:string;url:string}[]};

export default function Home(){
 const [topic,setTopic]=useState(''); const [busy,setBusy]=useState(false); const [result,setResult]=useState<Result|null>(null); const [page,setPage]=useState(0); const refs=useRef<any[]>([]);
 async function generate(){
  if(!topic.trim()) return Alert.alert('Maite Lab','Escribe un tema primero.');
  if(API.includes('REEMPLAZAR')) return Alert.alert('Configuración pendiente','Hay que conectar la app con el servidor de IA.');
  setBusy(true); setResult(null);
  try{const r=await fetch(`${API}/api/generate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({topic})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Error');setResult(d);setPage(0)}catch(e:any){Alert.alert('No pude generar el contenido',e.message)}finally{setBusy(false)}
 }
 async function save(i:number){try{const uri=await captureRef(refs.current[i],{format:'png',quality:1,result:'tmpfile'});const perm=await MediaLibrary.requestPermissionsAsync();if(!perm.granted){Alert.alert('Permiso necesario','Autoriza a Maite Lab a guardar imágenes en Fotos.');return}await MediaLibrary.saveToLibraryAsync(uri);Alert.alert('Listo ✨','La lámina quedó guardada en Fotos.')}catch(e){Alert.alert('Error','No pude guardar la imagen.')}}
 async function share(i:number){try{const uri=await captureRef(refs.current[i],{format:'png',quality:1,result:'tmpfile'});if(await Sharing.isAvailableAsync())await Sharing.shareAsync(uri,{mimeType:'image/png',dialogTitle:'Compartir en Instagram'});else await Share.share({message:'Contenido creado con Maite Lab'});}catch(e){Alert.alert('Error','No pude compartir la lámina.')}}
 const slide=result?.slides?.[page];
 return <View style={s.root}><StatusBar style="dark"/><ScrollView contentContainerStyle={s.content}>
  <View style={s.top}><Text style={s.logo}>MAITE<Text style={s.logoAccent}>LAB</Text> ✦</Text><View style={s.pill}><Text style={s.pillText}>IA EDUCATIVA</Text></View></View>
  {!result && <><View style={s.hero}><Text style={s.h1}>Aprende cosas que no sabías que querías saber.</Text><Text style={s.lead}>Tú pones el tema. Maite Lab investiga, verifica y crea tu contenido para Instagram.</Text></View>
   <View style={s.box}><Text style={s.label}>¿Qué quieres descubrir hoy?</Text><TextInput value={topic} onChangeText={setTopic} placeholder="Ej: La medusa que es inmortal" placeholderTextColor="#938ca0" multiline style={s.input}/>
    <TouchableOpacity style={s.primary} onPress={generate} disabled={busy}><Text style={s.primaryText}>{busy?'🔎 INVESTIGANDO…':'✨ CREAR MI CONTENIDO'}</Text></TouchableOpacity>
    <View style={s.chips}>{['🪼 Medusa inmortal','💭 ¿Por qué soñamos?','🕳️ Agujeros negros'].map(x=><TouchableOpacity key={x} style={s.chip} onPress={()=>setTopic(x.slice(2))}><Text style={s.chipText}>{x}</Text></TouchableOpacity>)}</View>
   </View></>}
  {result && <><View style={s.resultHead}><TouchableOpacity onPress={()=>setResult(null)}><Ionicons name="arrow-back" size={24} color="#171326"/></TouchableOpacity><View style={{flex:1}}><Text style={s.resultTitle}>{result.title}</Text><Text style={s.resultSub}>{result.subtitle}</Text></View></View>
   <View style={s.wow}><Text style={s.wowTitle}>⚡ DATO WOW</Text><Text style={s.wowText}>{result.wow}</Text></View>
   <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:12}}>{result.cards?.map(c=><View key={c.title} style={s.card}><Text style={s.cardTitle}>{c.title}</Text><Text style={s.cardText}>{c.text}</Text></View>)}</ScrollView>
   {slide && <><View style={s.counter}><Text style={s.counterText}>{page+1} / {result.slides.length}</Text></View><View ref={r=>refs.current[page]=r} collapsable={false} style={s.slide}><Text style={s.slideBrand}>MAITE LAB ✦</Text><View><Text style={s.hook}>{slide.hook}</Text><Text style={s.slideTitle}>{slide.title}</Text><Text style={s.slideText}>{slide.text}</Text></View><Text style={s.slideFooter}>Aprende algo nuevo. Compártelo.</Text></View>
    <View style={s.actions}><TouchableOpacity style={s.action} onPress={()=>save(page)}><Ionicons name="download-outline" size={22} color="#7657ff"/><Text style={s.actionText}>Guardar</Text></TouchableOpacity><TouchableOpacity style={s.action} onPress={()=>share(page)}><Ionicons name="share-social-outline" size={22} color="#7657ff"/><Text style={s.actionText}>Instagram</Text></TouchableOpacity></View>
    <View style={s.nav}><TouchableOpacity disabled={page===0} onPress={()=>setPage(p=>Math.max(0,p-1))}><Text style={[s.navText,page===0&&s.disabled]}>← Anterior</Text></TouchableOpacity><TouchableOpacity disabled={page===result.slides.length-1} onPress={()=>setPage(p=>Math.min(result.slides.length-1,p+1))}><Text style={[s.navText,page===result.slides.length-1&&s.disabled]}>Siguiente →</Text></TouchableOpacity></View></>}
   <Text style={s.sourceTitle}>Fuentes verificadas</Text>{result.sources?.map(x=><TouchableOpacity key={x.url} onPress={()=>Share.share({message:x.url})}><Text style={s.source}>• {x.title}</Text></TouchableOpacity>)}
  </>}
 </ScrollView></View>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#faf8ff'},content:{padding:22,paddingBottom:50},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:30},logo:{fontSize:24,fontWeight:'900',color:'#171326'},logoAccent:{color:'#7657ff'},pill:{backgroundColor:'#eeeaff',paddingHorizontal:10,paddingVertical:7,borderRadius:20},pillText:{fontSize:10,fontWeight:'900',color:'#5d48b7'},hero:{marginBottom:25},h1:{fontSize:43,lineHeight:42,fontWeight:'900',letterSpacing:-1.7,color:'#171326'},lead:{fontSize:18,lineHeight:26,color:'#686174',marginTop:15},box:{backgroundColor:'#fff',borderWidth:1,borderColor:'#e6e1ef',borderRadius:24,padding:18},label:{fontSize:14,fontWeight:'900',marginBottom:10},input:{minHeight:110,borderWidth:2,borderColor:'#e2dced',borderRadius:17,padding:16,fontSize:18,color:'#171326',textAlignVertical:'top'},primary:{backgroundColor:'#7657ff',borderRadius:15,padding:17,alignItems:'center',marginTop:12},primaryText:{color:'#fff',fontWeight:'900',fontSize:15},chips:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:12},chip:{backgroundColor:'#f1eef7',padding:10,borderRadius:12},chipText:{fontSize:12,fontWeight:'700',color:'#4e475b'},resultHead:{flexDirection:'row',gap:12,alignItems:'center'},resultTitle:{fontSize:30,fontWeight:'900'},resultSub:{color:'#6b6474',marginTop:3},wow:{backgroundColor:'#171326',borderRadius:20,padding:20,marginVertical:18},wowTitle:{color:'#bdb0ff',fontWeight:'900',fontSize:12},wowText:{color:'#fff',fontSize:20,lineHeight:29,fontWeight:'700',marginTop:8},card:{width:230,minHeight:130,backgroundColor:'#fff',borderRadius:18,padding:17,borderWidth:1,borderColor:'#e6e1ef'},cardTitle:{fontWeight:'900',fontSize:16,marginBottom:8},cardText:{color:'#625b6d',lineHeight:20},counter:{alignItems:'center',marginTop:24,marginBottom:8},counterText:{fontWeight:'900',color:'#6c6478'},slide:{width:W-44,height:(W-44)*16/9,borderRadius:24,padding:25,justifyContent:'space-between',backgroundColor:'#7657ff'},slideBrand:{color:'#fff',fontWeight:'900',fontSize:13,opacity:.8},hook:{color:'#e5ddff',fontSize:13,fontWeight:'900',letterSpacing:1,textTransform:'uppercase'},slideTitle:{color:'#fff',fontSize:34,lineHeight:38,fontWeight:'900',marginVertical:14},slideText:{color:'#fff',fontSize:18,lineHeight:26},slideFooter:{color:'#fff',fontWeight:'800',fontSize:12,opacity:.8},actions:{flexDirection:'row',gap:10,marginTop:12},action:{flex:1,backgroundColor:'#fff',borderRadius:15,padding:13,alignItems:'center',flexDirection:'row',justifyContent:'center',gap:7},actionText:{fontWeight:'900',color:'#4e3caa'},nav:{flexDirection:'row',justifyContent:'space-between',paddingVertical:18},navText:{fontWeight:'900',color:'#5e45d2'},disabled:{color:'#b8b1c1'},sourceTitle:{fontSize:18,fontWeight:'900',marginTop:15,marginBottom:10},source:{color:'#5d45cf',lineHeight:23,marginBottom:8}});
